### ISSUE TITLE
How can I change the size of drawer

### ISSUE THREAD

**Issue by HakobiDev** [nativescript-vue/nativescript-vue-multi-drawer#13]

**Comment by rigor789** [comment]
Pass in the width to options, each drawer defines a width: https://github.com/nativescript-vue/nativescript-vue-multi-drawer/blob/d751f6e366b5831a24abdf74543cbc3ad0aa61f6/index.js#L9

**Comment by HakobiDev** [comment]
Thanks for your plugin, I love it so much!
